### ISSUE TITLE
DynamicValueLookup for properties

### ISSUE THREAD

**Issue by BenasJacikas** [nihaue/TRex#10]
I need to support model similar to this:

```
public class Company 
{
    public string Name { get; }
    [DynamicValueLookup("GetCountries", "Countries", "Id", "Name")]
    public string CountryOfOrigin { get; }

    public Company(string name, string countryOfOrigin) 
    {
        Name = name;
        CountryOfOrigin = countryOfOrigin;
    }
}
```

Are there any reasons not to support DynamicValueLookup for properties?

**Comment by nihaue** [comment]
I'm not sure if the Power Apps or Logic Apps designer supports resolving dynamic values for model properties. I will investigate. If it does, I will work to implement that style of usage – which shouldn’t be too difficult if it works anything like dynamic values for operation parameters themselves.

**Comment by BenasJacikas** [comment]
It does, I checked

I can create example if it's needed

**Comment by nihaue** [comment]
Yeah that would be great. If you have an example swagger file that I can test with then it shouldn't be too difficult to implement.

**Comment by nihaue** [comment]
I should have this integrated into the next version of T-Rex. I have the code written, but haven't built-out a sample for it yet and/or validated within the designer itself.
