### ISSUE TITLE
Documentation - push triggerswith no required input

### ISSUE THREAD

**Issue by AndyEdmonds** [nihaue/TRex#3]
In your section on push triggers in the documentation you start the sentence "if you don" and then don't finish it. You were going to tell us what to do if we don't want an input to the trigger, just outputs. 
Could you tell me what this is? I have a push trigger that doesn't need an input, i.e. the trigger should fire for every event.

**Comment by nihaue** [comment]
Good catch. Essentially there are two separate generic classes that can be used as the type for the input parameter. One that contains two type parameters TInput, TOutput, and one that contains just TOutput. Unfortunately, the representation of generic class names contains angled brackets which weren't being rendered correctly (e.g., `ClassName<T>` was rendered simply as ClassName). I adjusted the docs to make them display correctly, which should make a lot of things a lot more clear.

Thanks!
