### ISSUE TITLE
DynamicModelBase should support declaring property names at runtime

### ISSUE THREAD

**Issue by cmshawns** [nihaue/TRex#9]
We have a situation where each record can include entities whose property names are not known until the record is retrieved from the data source at runtime. The current version of `DynamicModelBase` expects an object where the property names are known at compile time.

I intend to address this need myself and submit a pull request. What I'm thinking is to add one or more constructor overrides that can take a `JObject` and/or dictionary.

**Comment by nihaue** [comment]
It does already support this. You just need to implement an **empty constructor** on the class that derives from DynamicModelBase if desired, and then ensure that your using the **dynamic** keyword when new-ing up the instance. The properties are backed by a JToken in the background by default.

Example below:

```
   public class ValuesController : ApiController
    {
        // GET api/values/5
        public Foo Get(int id)
        {
            // Step 2: dynamic keyword 
            dynamic dynamicFoo = new Foo();
            dynamicFoo.prop = "value";
            dynamicFoo.prop2 = "anotherValue";

            return dynamicFoo;
        }
    }

    public class Foo : DynamicModelBase
    {
        // Step 1: Constructor that doesn't require parameters
        public Foo()
        {

        }
        public Foo(object source) : base(source)
        {
        }
    }
```

Sample output:
Request URL
http://yourapi.example.org/api/Values/1

Response Body
```
{
  "prop": "value",
  "prop2": "anotherValue"
}
```

**Comment by nihaue** [comment]
Also, you should be able to use a JToken as the "source" object if you want to accomplish dynamic property names at runtime (after re-reading that's what you're actually after).

Essentially the DynamicModelBase turns your class into an object that takes the shape of whatever is passed in as the source, and allows dynamic addition of members at any time thereafter -- while also allowing you to explicitly declare certain members that are common to all instances.

The values themselves are stored in a private JToken instance inside the base class.

**Comment by cmshawns** [comment]
Yes, that's pretty much what I've done - by adding a `DynamicModelBase(JToken)` constructor. It seems to be working pretty smoothly :-)

**Comment by nihaue** [comment]
Yeah it would even work just fine with a dictionary if you didn't want to add custom constructors.

Sample Model
```
    public class Foo : DynamicModelBase
    {
        public int FieldCommonToAllRecords { get; set; }
        public Foo(object source) : base(source) { }
    }
```

Sample Controller
```
    public class ValuesController : ApiController
    {
        public Foo Get(int id)
        {
            // Dynamic properties at runtime
            var valuesFromDatabase = new Dictionary<string, object>();
            
            // Dictionary items could have been added anywhere
            valuesFromDatabase.Add("column1", "valueForCol1");
            valuesFromDatabase.Add("column2", "valueForCol2");
            
            var foo = new Foo(valuesFromDatabase);
            foo.FieldCommonToAllRecords = 5;

            return foo;
        }
    }

```
Sample Output
```
{
  "column1": "valueForCol1",
  "column2": "valueForCol2",
  "FieldCommonToAllRecords": 5
}
```

**Comment by nihaue** [comment]
So am I good to close this issue, or is there something still missing?

**Comment by nihaue** [comment]
I have documented a few different approaches for setting properties in the form of [unit tests that you can find over here](https://github.com/nihaue/TRex/blob/powerapps/Source/TRex.Metadata.Tests/DynamicModelBaseTests.cs#L58-L107).

**Comment by cmshawns** [comment]
Sorry I dropped off there :-( Yes, I'm good now with just using dictionaries. Thanks for all your help :-)
